version: "3.8"
services:
  car_app:
    image: leandrosilva/php5.6-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  car_db:
    image: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
